# -*- coding: utf-8 -*-
"""Copy of FDS-AD8311

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NT2kvN3ZZF23e-RDYE0C9YQB3O5q4udf

all Thursday between two given days
"""

import pandas as pd
vis  = pd.date_range('2020-03-10', 
                           '2020-12-31', freq="W-THU")
print("All Thursdays between 2020-03-10 and 2020-12-31:\n")
print(vis.values)

"""DataFrame birds from the dictionary data which has the index labels

"""

import pandas as pd

data = {'birds': ['Cranes', 'Cranes', 'plovers', 'spoonbills', 'spoonbills', 'Cranes', 'plovers', 'Cranes', 'spoonbills', 'spoonbills'],
    'age': [3.5, 4, 1.5, np.nan, 6, 3, 5.5, np.nan, 8, 4],
    'visits': [2, 4, 3, 4, 3, 4, 2, 2, 3, 2],
    'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

data['labels'] = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, columns=['birds', 'age', 'visits', 'priority', 'labels'])
df.set_index('labels')

"""the first 2 rows of the birds DataFrame"""

print(df.head(2))

"""all the rows with only'birds' and 'age' columns from the dataframe"""

print(df['birds'])
print(df['age'])

"""all the rows with only'visits' and 'priority' columns from the dataframe"""

print(df['visits'])
print(df['priority'])

"""select the rows with columns ['birds','visits'] where has the age is missing(e.g)NaN"""

df[df['age'].isnull()]

