# -*- coding: utf-8 -*-
"""Copy of vishwa of wbna.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12yv7T_DqY1sdqxVhBAAhGhbFWLipxIBz
"""

import pandas as pd
vishwa = pd.read_csv("/content/wba.csv")
print(vishwa)

import pandas as pd
freq_dis_PTS=vishwa['PTS'].value_counts() 
print(freq_dis_PTS)

import pandas as pd
freq_dis_PTS= vishwa['PTS'].value_counts().sort_index(ascending=True)
print(freq_dis_PTS)

import pandas as pd
percentage_PTS= vishwa['PTS'].value_counts(normalize=True).sort_index()*100
print(percentage_PTS)

